version: "3.9"
services:
  cache:
    image: redis:7.0.5-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - cache
    ports:
      - "8082:8081"
    environment:
      - GRPC_SERVER_ADDRESS=
      - HANDLER_TIMEOUT=3
      - REDIS_PORT=
      - REDIS_HOST=
      - REFRESH_TOKEN_EXP=259200
      - ID_TOKEN_EXP=3600
      - PUB_KEY_FILE=
      - PRIV_KEY_FILE=
      - REFRESH_SECRET=
      - BASE_URL=
volumes:
  cache:
    driver: local