apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-app-deployment
  labels:
    app: grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
      - name: grpc-client
        image: 074047115132.dkr.ecr.us-east-1.amazonaws.com/client:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
          - name: REDIS_HOST
            value: redis-master
          - name: REDIS_PORT
            value: "6379"
          - name: PRIV_KEY_FILE
            value: ./rsa_private.pem
          - name: PUB_KEY_FILE
            value: ./rsa_public.pem
          - name: ID_TOKEN_EXP
            value: "3600"
          - name: REFRESH_TOKEN_EXP
            value: "259200"
          - name: BASE_URL
            value: /api
          - name: REFRESH_SECRET
            value: <:>thisismysecretkey223344&&$$!?<
          - name: HANDLER_TIMEOUT
            value: "3"
