apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-app-deployment
  labels:
    app: grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
      - name: grpc-client
        image: ""
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
          - name: REDIS_HOST
            value: ""
          - name: REDIS_PORT
            value: ""
          - name: PRIV_KEY_FILE
            value: ""
          - name: PUB_KEY_FILE
            value: ""
          - name: ID_TOKEN_EXP
            value: "3600"
          - name: REFRESH_TOKEN_EXP
            value: "259200"
          - name: BASE_URL
            value: ""
          - name: REFRESH_SECRET
            value: ""
          - name: HANDLER_TIMEOUT
            value: "3"
